version: '3.9'

services:
    mongodb:
        container_name: mongodb
        image: mongo
        build:
            context: ./service/mongodb
            dockerfile: Dockerfile
        env_file:
            - ./service/mongodb/.env
        volumes:
            - mongodb_volume:/data/db
        ports:
            - '27017:27017'
        networks:
            - u_dong
        restart: always
        tty: true
    nestjs:
        container_name: nestjs
        image: nestjs
        build:
            context: ./service/nestjs
            dockerfile: Dockerfile
        env_file:
            - ./service/nestjs/.env
        volumes:
            - nestjs_src_volume:/app/src
            - nestjs_log_volume:/app/log
        networks:
            - u_dong
        depends_on:
            - mongodb
        restart: always
        tty: true
    react:
        container_name: react
        image: react
        build:
            context: ./service/react
            dockerfile: Dockerfile
            args:
                - REACT_APP_SERVER=${REACT_APP_SERVER:-http://localhost:3000}
        env_file:
            - ./service/react/.env
        volumes:
            - react_src_volume:/app/src
        networks:
            - u_dong
        depends_on:
            - nestjs
        restart: always
        tty: true
    nginx:
        container_name: nginx
        image: nginx
        build:
            context: ./service/nginx
            dockerfile: Dockerfile
        env_file:
            - ./service/nginx/.env
        ports:
            - 80:80
            - 443:443
        volumes:
            - nginx_log_volume:/var/log/nginx
        networks:
            - u_dong
        depends_on:
            - react
        restart: always
        tty: true

volumes:
    react_src_volume:
        name: react_src_volume
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./service/react/src
    nestjs_src_volume:
        name: nestjs_src_volume
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./service/nestjs/src
    nestjs_log_volume:
        name: nestjs_log_volume
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./service/nestjs/log
    mongodb_volume:
        name: mongodb_volume
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./service/mongodb/db
    nginx_log_volume:
        name: nginx_log_volume
        driver: local
        driver_opts:
            device: ./service/nginx/log
            type: none
            o: bind

networks:
    u_dong:
        name: u_dong
